import { IconNailDesignChallange, IconPremiumNailKit } from "@/assets/icons";

export const carouselData = [
  {
    id: 1,
    title: "Today's Income",
    value: "$250",
    image: require("@/assets/images/carouse-image-one.png"),
  },
  {
    id: 2,
    title: "Appointments",
    value: "5 / 16",
    image: require("@/assets/images/carouse-image-one.png"),
  },
  {
    id: 3,
    title: "Tasks Completed",
    value: "8",
    image: require("@/assets/images/carouse-image-one.png"),
  },
];

export const weeklyTasks = [
  { id: 1, text: "Restock gel polishes", completed: false },
  { id: 2, text: "Update client records", completed: true },
  { id: 3, text: "Clean and sanitize tools", completed: true },
];

export const weeklyToDoList = [
  { id: 1, text: "Restock gel polishes", completed: false },
  { id: 2, text: "Update client records", completed: true },
  { id: 4, text: "Restock gel polishes", completed: false },
  { id: 5, text: "Update client records", completed: true },
  { id: 6, text: "Clean and sanitize tools", completed: true },
  { id: 3, text: "Clean and sanitize tools", completed: true },
];

export const sections = [
  {
    title: "Popular",
    data: [
      {
        id: 1,
        title: "Acrylic Nail Art Masterclass",
        instructor: "Emma Wilson",
        duration: "4h 20m",
        points: 100,
        price: 29.0,
        image: require("@/assets/images/nail-image.png"),
        subscribed: false,
        progress: 0,
      },
      {
        id: 2,
        title: "Gel Polish Perfection",
        instructor: "Olivia Brown",
        duration: "3h 10m",
        points: 80,
        price: 25.0,
        image: require("@/assets/images/3d_avatar_12.png"),
        subscribed: false,
        progress: 0,
      },
      {
        id: 3,
        title: "Creative Ombre Nail Design",
        instructor: "Sophia Turner",
        duration: "2h 45m",
        points: 70,
        price: 22.0,
        image: require("@/assets/images/nail-image.png"),
        subscribed: false,
        progress: 0,
      },
      {
        id: 4,
        title: "Professional Nail Extensions 101",
        instructor: "Lily Adams",
        duration: "5h 00m",
        points: 110,
        price: 32.0,
        image: require("@/assets/images/3d_avatar_12.png"),
        subscribed: false,
        progress: 0,
      },
    ],
  },
  {
    title: "My Subscribed",
    data: [
      {
        id: 5,
        title: "Acrylic Nail Art Masterclass",
        instructor: "Emma Wilson",
        duration: "4h 20m",
        points: 100,
        price: 29.0,
        image: require("@/assets/images/nail-image.png"),
        subscribed: true,
        progress: 65,
      },
      {
        id: 6,
        title: "Luxury Nail Finishing",
        instructor: "Sophia Lee",
        duration: "3h 50m",
        points: 95,
        price: 27.0,
        image: require("@/assets/images/3d_avatar_12.png"),
        subscribed: true,
        progress: 30,
      },
      {
        id: 7,
        title: "Nail Care & Hygiene Essentials",
        instructor: "Ava Thompson",
        duration: "2h 30m",
        points: 60,
        price: 18.0,
        image: require("@/assets/images/nail-image.png"),
        subscribed: true,
        progress: 80,
      },
    ],
  },
  {
    title: "Trending",
    data: [
      {
        id: 8,
        title: "Luxury Nail Techniques",
        instructor: "Sophia Turner",
        duration: "5h 10m",
        points: 120,
        price: 35.0,
        image: require("@/assets/images/nail-image.png"),
        subscribed: false,
        progress: 0,
      },
      {
        id: 9,
        title: "French Manicure Redefined",
        instructor: "Isabella Green",
        duration: "3h 40m",
        points: 90,
        price: 26.0,
        image: require("@/assets/images/3d_avatar_12.png"),
        subscribed: false,
        progress: 0,
      },
      {
        id: 10,
        title: "Minimal Nail Art Styles",
        instructor: "Luna Evans",
        duration: "2h 55m",
        points: 75,
        price: 21.0,
        image: require("@/assets/images/nail-image.png"),
        subscribed: false,
        progress: 0,
      },
      {
        id: 11,
        title: "Nail Photography for Professionals",
        instructor: "Ava Smith",
        duration: "3h 25m",
        points: 85,
        price: 28.0,
        image: require("@/assets/images/3d_avatar_12.png"),
        subscribed: false,
        progress: 0,
      },
    ],
  },
];

export const popelerData = [
  {
    id: 1,
    instructor: "Emma Wilson",
    duration: "4h 20m",
    points: 100,
    price: 29.0,
    image: require("@/assets/images/nail-image.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 2,
    instructor: "Olivia Brown",
    duration: "3h 10m",
    points: 80,
    price: 25.0,
    image: require("@/assets/images/3d_avatar_12.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 3,
    instructor: "Sophia Turner",
    duration: "2h 45m",
    points: 70,
    price: 22.0,
    image: require("@/assets/images/nail-image.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 4,
    instructor: "Lily Adams",
    duration: "5h 00m",
    points: 110,
    price: 32.0,
    image: require("@/assets/images/3d_avatar_12.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 5,
    instructor: "Emma Wilson",
    duration: "4h 20m",
    points: 100,
    price: 29.0,
    image: require("@/assets/images/nail-image.png"),
    subscribed: true,
    progress: 65,
  },
  {
    id: 6,
    instructor: "Sophia Lee",
    duration: "3h 50m",
    points: 95,
    price: 27.0,
    image: require("@/assets/images/3d_avatar_12.png"),
    subscribed: true,
    progress: 30,
  },
  {
    id: 7,
    instructor: "Ava Thompson",
    duration: "2h 30m",
    points: 60,
    price: 18.0,
    image: require("@/assets/images/nail-image.png"),
    subscribed: true,
    progress: 80,
  },
  {
    id: 8,
    instructor: "Sophia Turner",
    duration: "5h 10m",
    points: 120,
    price: 35.0,
    image: require("@/assets/images/nail-image.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 9,
    instructor: "Isabella Green",
    duration: "3h 40m",
    points: 90,
    price: 26.0,
    image: require("@/assets/images/3d_avatar_12.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 10,
    instructor: "Luna Evans",
    duration: "2h 55m",
    points: 75,
    price: 21.0,
    image: require("@/assets/images/nail-image.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 11,
    instructor: "Ava Smith",
    duration: "3h 25m",
    points: 85,
    price: 28.0,
    image: require("@/assets/images/3d_avatar_12.png"),
    subscribed: false,
    progress: 0,
  },
];
export const nailData = [
  {
    id: 1,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "4h 20m",
    points: 100,
    price: 29.0,
    image: require("@/assets/images/nail-image-view.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 2,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "3h 10m",
    points: 80,
    price: 25.0,
    image: require("@/assets/images/nail-image-view.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 3,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "2h 45m",
    points: 70,
    price: 22.0,
    image: require("@/assets/images/nail-image-view.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 4,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "5h 00m",
    points: 110,
    price: 32.0,
    image: require("@/assets/images/nail-image-view.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 5,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "4h 20m",
    points: 100,
    price: 29.0,
    image: require("@/assets/images/nail-image-view.png"),
    subscribed: true,
    progress: 65,
  },
  {
    id: 6,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "3h 50m",
    points: 95,
    price: 27.0,
    image: require("@/assets/images/nail-image-view.png"),
    subscribed: true,
    progress: 30,
  },
  {
    id: 7,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "2h 30m",
    points: 60,
    price: 18.0,
    image: require("@/assets/images/nail-image-view.png"),
    subscribed: true,
    progress: 80,
  },
  {
    id: 8,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "5h 10m",
    points: 120,
    price: 35.0,
    image: require("@/assets/images/nail-image-view.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 9,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "3h 40m",
    points: 90,
    price: 26.0,
    image: require("@/assets/images/nail-image-view.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 10,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "2h 55m",
    points: 75,
    price: 21.0,
    image: require("@/assets/images/nail-image-view.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 11,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "3h 25m",
    points: 85,
    price: 28.0,
    image: require("@/assets/images/nail-image-view.png"),
    subscribed: false,
    progress: 0,
  },
];
export const mainData = [
  {
    id: 1,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "4h 20m",
    points: 100,
    price: 29.0,
    image: require("@/assets/images/main-mood.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 2,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "3h 10m",
    points: 80,
    price: 25.0,
    image: require("@/assets/images/main-mood.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 3,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "2h 45m",
    points: 70,
    price: 22.0,
    image: require("@/assets/images/main-mood.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 4,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "5h 00m",
    points: 110,
    price: 32.0,
    image: require("@/assets/images/main-mood.png"),
    subscribed: false,
    progress: 0,
  },
  {
    id: 5,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "4h 20m",
    points: 100,
    price: 29.0,
    image: require("@/assets/images/main-mood.png"),
    subscribed: true,
    progress: 65,
  },
  {
    id: 6,
    instructor: "Premium Gel Polish Set - Summer Collection",
    duration: "3h 50m",
    points: 95,
    price: 27.0,
    image: require("@/assets/images/main-mood.png"),
    subscribed: true,
    progress: 30,
  },
];

export const rewardData = [
  {
    id: 1,
    title: "Nail Design Challenge",
    date: "Today",
    points: "+25",
    icon: IconNailDesignChallange, // custom svg or name
  },
  {
    id: 2,
    title: "Nail Design Challenge",
    date: "Today",
    points: "+25",
    icon: IconNailDesignChallange,
  },
  {
    id: 3,
    title: "Premium Nail Kit",
    date: "Oct 16",
    points: "+25",
    icon: IconPremiumNailKit,
  },
  {
    id: 4,
    title: "Premium Nail Kit",
    date: "Oct 16",
    points: "+25",
    icon: IconPremiumNailKit,
  },
];

export const productData = [
  {
    id: 1,
    title: "Premium Gel Polish Set - Summer Collection",
    price: "$42.99",
    points: "+50 pts",
    image: require("@/assets/images/nail-image-view.png"),
    category: "Gel Polish",
  },
  {
    id: 2,
    title: "Premium Gel Polish Set - Summer Collection",
    price: "$42.99",
    points: "+50 pts",
    image: require("@/assets/images/nail-image-view.png"),
    category: "Gel Polish",
  },
  {
    id: 3,
    title: "Premium Nail Kit",
    price: "$39.99",
    points: "+40 pts",
    image: require("@/assets/images/nail-image-view.png"),
    category: "Nail Art",
  },
  {
    id: 4,
    title: "Professional Nail Tools",
    price: "$45.99",
    points: "+60 pts",
    image: require("@/assets/images/nail-image-view.png"),
    category: "Tools",
  },
];

export const albums = [
  {
    id: 1,
    title: "French Tips",
    images: 8,
    thumbnail: require("@/assets/images/nail-image-view.png"),
  },
  {
    id: 2,
    title: "Minimal",
    images: 8,
    thumbnail: require("@/assets/images/nail-image-view.png"),
  },
  {
    id: 3,
    title: "Bridal Collection",
    images: 8,
    thumbnail: require("@/assets/images/nail-image-view.png"),
  },
];
